### ISSUE TITLE
NTP offset

### ISSUE THREAD

**Issue by ctappy** [xorpaul/check_linux#1]
https://github.com/xorpaul/check_linux/blob/13f9f57e76d53821174f85232d2d37a3c016647a/check_linux.rb#L376

I believe should be `ntp_offset = (ntp_data[-2].to_f / 1000).abs`

if it is a negative number the offset will not be greater the the absolute value you don't want to offset to go over

**Comment by xorpaul** [comment]
Thanks, fixed https://github.com/xorpaul/check_linux/commit/e8146667814201f40599d1c7ca7f3ef44fcb5a40#diff-e6a9213abeae2c91282e199465467a4eR445
